// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNet_projektni.Data;

#nullable disable

namespace dotNet_projektni.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Groceries"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Fruits & Vegetables"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dairy & Eggs"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Meat & Seafood"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Bakery"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Beverages"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Pantry Staples"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Frozen Foods"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Snacks"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Health & Beauty"
                        });
                });

            modelBuilder.Entity("Model.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 3,
                            IsPurchased = false,
                            Name = "Milk",
                            Quantity = 2,
                            ShoppingListId = 1,
                            Unit = "liters"
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 5,
                            IsPurchased = false,
                            Name = "Bread",
                            Quantity = 1,
                            ShoppingListId = 1,
                            Unit = "loaf"
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 2,
                            IsPurchased = false,
                            Name = "Apples",
                            Quantity = 6,
                            ShoppingListId = 1,
                            Unit = "pieces"
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 4,
                            IsPurchased = false,
                            Name = "Chicken Breast",
                            Quantity = 1,
                            ShoppingListId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 2,
                            IsPurchased = false,
                            Name = "Tomatoes",
                            Quantity = 3,
                            ShoppingListId = 1,
                            Unit = "pieces"
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 6,
                            IsPurchased = false,
                            Name = "Red Wine",
                            Quantity = 2,
                            ShoppingListId = 2,
                            Unit = "bottles"
                        },
                        new
                        {
                            ItemId = 7,
                            CategoryId = 4,
                            IsPurchased = false,
                            Name = "Salmon Fillets",
                            Quantity = 4,
                            ShoppingListId = 2,
                            Unit = "pieces"
                        },
                        new
                        {
                            ItemId = 8,
                            CategoryId = 7,
                            IsPurchased = false,
                            Name = "Pasta",
                            Quantity = 2,
                            ShoppingListId = 2,
                            Unit = "boxes"
                        },
                        new
                        {
                            ItemId = 9,
                            CategoryId = 2,
                            IsPurchased = false,
                            Name = "Fresh Basil",
                            Quantity = 1,
                            ShoppingListId = 2,
                            Unit = "bunch"
                        },
                        new
                        {
                            ItemId = 10,
                            CategoryId = 3,
                            IsPurchased = false,
                            Name = "Cheese",
                            Quantity = 500,
                            ShoppingListId = 2,
                            Unit = "grams"
                        },
                        new
                        {
                            ItemId = 11,
                            CategoryId = 6,
                            IsPurchased = false,
                            Name = "Coffee Beans",
                            Quantity = 1,
                            ShoppingListId = 3,
                            Unit = "kg"
                        },
                        new
                        {
                            ItemId = 12,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Crackers",
                            Quantity = 3,
                            ShoppingListId = 3,
                            Unit = "boxes"
                        },
                        new
                        {
                            ItemId = 13,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Cookies",
                            Quantity = 2,
                            ShoppingListId = 3,
                            Unit = "boxes"
                        },
                        new
                        {
                            ItemId = 14,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Nuts Mix",
                            Quantity = 500,
                            ShoppingListId = 3,
                            Unit = "grams"
                        },
                        new
                        {
                            ItemId = 15,
                            CategoryId = 3,
                            IsPurchased = false,
                            Name = "Eggs",
                            Quantity = 12,
                            ShoppingListId = 4,
                            Unit = "pieces"
                        },
                        new
                        {
                            ItemId = 16,
                            CategoryId = 3,
                            IsPurchased = false,
                            Name = "Yogurt",
                            Quantity = 4,
                            ShoppingListId = 4,
                            Unit = "cups"
                        },
                        new
                        {
                            ItemId = 17,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Granola",
                            Quantity = 1,
                            ShoppingListId = 4,
                            Unit = "box"
                        },
                        new
                        {
                            ItemId = 18,
                            CategoryId = 6,
                            IsPurchased = false,
                            Name = "Orange Juice",
                            Quantity = 1,
                            ShoppingListId = 4,
                            Unit = "liter"
                        },
                        new
                        {
                            ItemId = 19,
                            CategoryId = 7,
                            IsPurchased = false,
                            Name = "Canned Beans",
                            Quantity = 6,
                            ShoppingListId = 5,
                            Unit = "cans"
                        },
                        new
                        {
                            ItemId = 20,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Trail Mix",
                            Quantity = 3,
                            ShoppingListId = 5,
                            Unit = "bags"
                        },
                        new
                        {
                            ItemId = 21,
                            CategoryId = 7,
                            IsPurchased = false,
                            Name = "Peanut Butter",
                            Quantity = 2,
                            ShoppingListId = 5,
                            Unit = "jars"
                        },
                        new
                        {
                            ItemId = 22,
                            CategoryId = 9,
                            IsPurchased = false,
                            Name = "Granola Bars",
                            Quantity = 10,
                            ShoppingListId = 5,
                            Unit = "pieces"
                        },
                        new
                        {
                            ItemId = 23,
                            CategoryId = 7,
                            IsPurchased = false,
                            Name = "Quinoa",
                            Quantity = 1,
                            ShoppingListId = 6,
                            Unit = "kg"
                        },
                        new
                        {
                            ItemId = 24,
                            CategoryId = 3,
                            IsPurchased = false,
                            Name = "Almond Milk",
                            Quantity = 2,
                            ShoppingListId = 6,
                            Unit = "liters"
                        },
                        new
                        {
                            ItemId = 25,
                            CategoryId = 2,
                            IsPurchased = false,
                            Name = "Spinach",
                            Quantity = 200,
                            ShoppingListId = 6,
                            Unit = "grams"
                        },
                        new
                        {
                            ItemId = 26,
                            CategoryId = 2,
                            IsPurchased = false,
                            Name = "Blueberries",
                            Quantity = 500,
                            ShoppingListId = 6,
                            Unit = "grams"
                        });
                });

            modelBuilder.Entity("Model.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShoppingListId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            ShoppingListId = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Essential items for the week",
                            Name = "Weekly Groceries",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 1
                        },
                        new
                        {
                            ShoppingListId = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Items needed for Saturday dinner",
                            Name = "Dinner Party Supplies",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 1
                        },
                        new
                        {
                            ShoppingListId = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Snacks and drinks for office",
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 2
                        },
                        new
                        {
                            ShoppingListId = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Morning essentials",
                            Name = "Breakfast Items",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 2
                        },
                        new
                        {
                            ShoppingListId = 5,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Non-perishable foods for camping",
                            Name = "Camping Trip",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 3
                        },
                        new
                        {
                            ShoppingListId = 6,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Description = "Organic and healthy foods",
                            Name = "Healthy Eating",
                            UpdatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Email = "john@example.com",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Email = "jane@example.com",
                            Username = "jane_smith"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 4, 20, 15, 47, 43, 537, DateTimeKind.Utc).AddTicks(9242),
                            Email = "mike@example.com",
                            Username = "mike_wilson"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Item", b =>
                {
                    b.HasOne("Model.Category", null)
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Model.ShoppingList", null)
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.ShoppingList", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Category", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("Model.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
